#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME="internet-check"
PROG="/usr/sbin/internet-check"

start_service() {
	local enabled

	config_load "$NAME"
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance main
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
